### ISSUE TITLE
Top and bottom pagination in twentyfifteen

### ISSUE THREAD

**Issue by imath** [imath/wp-idea-stream#22]
big black "move forward" and "move backward" black boxes. See above screenshots
![pagination-forward-top](https://cloud.githubusercontent.com/assets/1834524/6143074/5f18c342-b1c2-11e4-8579-662a48d2cc95.png)
pagination top forward

![pagination-forward-bottom](https://cloud.githubusercontent.com/assets/1834524/6143084/7ea5a0d6-b1c2-11e4-9037-894a8c73e675.png)
pagination bottom forward

![pagination-backward-top](https://cloud.githubusercontent.com/assets/1834524/6143098/b2673a4c-b1c2-11e4-8f6b-4ded7403c9c9.png)
pagination top backward

![pagination-backward-bottom](https://cloud.githubusercontent.com/assets/1834524/6143100/b7db93d8-b1c2-11e4-8289-4d15fcfd3b8c.png)
pagination bottom backward

We should include a fix in  ```templates/style.css``` chapter : 
/*--------------------------------------------------------------
2 - Pagination
--------------------------------------------------------------*/

**Comment by gregoirenoyelle** [comment]
Oups. I see. I will have a look.

**Comment by imath** [comment]
patch : https://gist.github.com/imath/6ffe9364f1c44a06b273
