### ISSUE TITLE
WP Idea Stream integrates perfectly with BuddyForms

### ISSUE THREAD

**Issue by romanzy** [imath/wp-idea-stream#27]
WP Idea Stream integrates perfectly with BuddyForms. When BuddyForms (http://tinyurl.com/q3e3q8u) is installed, users can create and edit Ideas on the BuddyPress front end. It's really cool!

**Comment by imath** [comment]
Glad to read this, but natively WP Idea Stream integrates with BuddyPress, you don't need BuddyForms :)

imath.
http://profiles.wordpress.org/imath/

**Comment by romanzy** [comment]
Look at the attached screen shot. It’s WP IIdea Stream integrated with BuddyForms. Maybe I used wrong words to express myself, but I don’t think you can do this without BuddyForms? Or do I miss something?

 I really love your work, Mathieu.

**Comment by romanzy** [comment]
Sorry, I forgot to include the DropBox link for the screenshot:

https://www.dropbox.com/s/nrc4aqyzuz1fg2b/21a.Nav_IdeaStream.jpg?dl=0

**Comment by imath** [comment]
Nice, so if everything works fine with BuddyForms, i guess we can close this issue. If i missed something don't hesitate to reopen it :)
