### ISSUE TITLE
Make Slugs Translateable

### ISSUE THREAD

**Issue by mrjarbenne** [imath/wp-idea-stream#29]
I've been working on a project to change some of the language used in idea-stream to use the plugin in a different context. I've been using po-edit, and I can't seem to translate the slugs from the defaults presented. Is it possible to use a language file to customize the slugs?

**Comment by imath** [comment]
Hi Jared,

It's possible to customize most of the slugs within the IdeaStream > settings menu in the WordPress Administration. Is it ok or are there some slugs i've forgotten ?

imath.
http://profiles.wordpress.org/imath/

**Comment by mrjarbenne** [comment]
No, you haven't missed any, and the amount of customization you allow for in the plugin is absolutely awesome. 

I'm going to assume that perhaps my use-case is very specific, and find a workaround that doesn't require you needing to do anything. :)

I've successfully removed all instances of the word "idea" to customize the plugin for another purpose. I was able to do all of that in a .po language file except for the default slugs, which still say idea and ideastream. I'm doing this customization for a multisite on which teachers will be activating the plugin on their own blogs (so I won't have an opportunity to tweak the slugs upon activation), and I was hoping to not have to have them go in and tweak the default slug given that I'm 99% of the way there with the language file. 

I'm thinking it's probably just as easy to hack the plugin, and then make the two changes again when you push out updates. 

Thanks for the incredible amount of work you've put into this. Translating it really highlighted how much detail you've included. 

Cheers.

**Comment by imath** [comment]
I see, i guess i forgot to include a __() function in default slugs. Will look at it asap.

imath.
http://profiles.wordpress.org/imath/

**Comment by mrjarbenne** [comment]
Sweet. Thanks. Check PayPal. Bought you a beer. 

Cheers.

**Comment by imath** [comment]
Thanks a lot @mrjarbenne :)

**Comment by imath** [comment]
@mrjarbenne this commit may be interesting for your project : https://github.com/imath/wp-idea-stream/commit/8a9c575a415eff4079d82e26b8dd2df7ba30c2e4
