### ISSUE TITLE
Multiple idea stream

### ISSUE THREAD

**Issue by davehakkens** [imath/wp-idea-stream#30]
Hi!

We would love to use the idea-stream plugin. 
However currently it's build as one big stream of ideas.

We want to ask the community to generate ideas for specific topics.
This means we would have multiple idea-streams running at once.

Some background about us:
We used to have this feature in our previous community and was very useful.
Recently we decided to make our community completely in Buddypress. 
Most people did discouraged this 'WP is made blogging'
However I love Wordpress and believe you can build a better community in here then most platforms out there.

So currently trying to proof them wrong. Spend the last months building and about 2 weeks ago we upgraded our community to WP:
https://davehakkens.nl/community/forums/

We like to keep things open so we put everything on Github:
https://github.com/hakkens/davehakkens

The only thing that is missing is something like the idea-steam plugin, it is for 90% want we are looking. 
Is it possible to customize this plugin, or build another version? We have some budget available...

Sorry for the long text!

Dave

**Comment by imath** [comment]
Just fyi: if you use the BuddyPress Groups component, then you can have an IdeaStream for each Group. Using this component would also help you to share private ideas in private groups.

The more i think about "Multiple IdeaStream" the more i think it would be very close to the bbPress plugin. And i think bbPress already does a pretty good job, so you might only need to customize the bbPress plugin to reach your goal.

**Comment by davehakkens** [comment]
Thanks for the group-tip. haven't looked into that yet.
I will also look into finding a way to customize Bbpress to our needs. I assume you have your hands full on other projects?  So if you know an suited developer we could do it, let me know!
