### ISSUE TITLE
Issue with Idea Comments and P2 Theme

### ISSUE THREAD

**Issue by mrjarbenne** [imath/wp-idea-stream#34]
With the P2 theme activated, Ideastream seems to struggle to allow users to add comments to an idea. I've set it up here: https://sandbox.commons.hwdsb.on.ca/inquirystream/inquiry/test-inquiry/

I recognize that P2 has got some funky ajax running in the background, which is probably the culprit, but I thought I would post the issue here just in case you have an idea for a fix. 

Cheers

**Comment by imath** [comment]
I have no idea what can be wrong but i'll try to understand what's going on. Thanks for your feedback

**Comment by mrjarbenne** [comment]
So sorry for the report. I've found the culprit. I had forgotten that @r-a-y had built me a custom template to make ideastream look better on P2 (the default page template on P2 has got a lot of extra header content). Removing that, removed the issue. Investigating further on my end.

**Comment by r-a-y** [comment]
Yeah, it was my fault :smile:

**Comment by mrjarbenne** [comment]
I was going to claim responsibility, but didn't want to look like I was taking the credit for the 99% that works. 😬

**Comment by mrjarbenne** [comment]
Let's share the fruits of our labour: 

https://github.com/hwdsbcommons/ideastream-p2-template

**Comment by imath** [comment]
@r-a-y @mrjarbenne Thanks a lot :)
