### ISSUE TITLE
Allow a simple "Like / Upvote" for an idea.

### ISSUE THREAD

**Issue by BoweFrankema** [imath/wp-idea-stream#48]
It would be very useful if a rating could be added using a simple "Like". So instead of having a 5 star rating you'd simply click "Vote for this Idea" and the star rating would be removed.

**Comment by imath** [comment]
Hi @BoweFrankema  thanks for your feedback.

Well it's already possible :)

https://wordpress.org/support/topic/weighted-voting?replies=2#post-7886332

In short, you can disable the built in rating system from the plugin's settings and then use the rating plugin of your choice.
