### ISSUE TITLE
i18n: split sentences / inconsistencies

### ISSUE THREAD

**Issue by naokomc** [imath/wp-idea-stream#53]
We've been translating the plugin in Japanese (we're giving it a spin for WordCamp Tokyo! :tokyo_tower: ) and I found i18n issues with some of the strings.

## Split sentences

(In [includes/admin/thanks.php#L49](https://github.com/imath/wp-idea-stream/blob/9a4273def03afb4f2d3e543bcbd0502c214b2134/includes/admin/thanks.php#L49
))
> Thank you for %1$s the latest version of WP Idea Stream! %2$s brings some really cool new features!

Since the word order differs between English and Japanese, we can't translate this split sentence. Please consider spelling out the whole sentence without including placeholders for "activating" and "upgrading to".

The strings below will not be translated correctly in Japanese either (links go to GlotPress strings):

- [from the group %s](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters[status]=either&filters[original_id]=1827050&sort[by]=translation_date_added&sort[how]=asc)
- [and posted from the group %s](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters[status]=either&filters[original_id]=1827051&sort[by]=translation_date_added&sort[how]=asc)
- [was posted in %s](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters[status]=either&filters[original_id]=1827227&sort[by]=translation_date_added&sort[how]=asc)
- [and tagged](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters[status]=either&filters[original_id]=1827228&sort[by]=translation_date_added&sort[how]=asc)
- [was tagged](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters[status]=either&filters[original_id]=1827229&sort[by]=translation_date_added&sort[how]=asc)
- [was posted](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters[status]=either&filters[original_id]=1827231&sort[by]=translation_date_added&sort[how]=asc)
- [by %s.]()
- [is the default status for all ideas](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters[status]=either&filters[original_id]=1826940&sort[by]=translation_date_added&sort[how]=asc)
- [the plugin&#39;s user profile becomes a new navigation in the BuddyPress member page.](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters[status]=either&filters[original_id]=1827087&sort[by]=translation_date_added&sort[how]=asc)

## "Idea Stream" or "IdeaStream" ?

The plugin is called "WP Idea Stream" but I also see several IdeaStream references ([GlotPress Search results for IdeaStream](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters%5Bterm%5D=IdeaStream&filters%5Buser_login%5D=&filters%5Bstatus%5D=current&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)). Is this intentional?

## Space before colons

There are strings with or without space before colons. To follow the WordPress convention, spaces from these should be removed ([GlotPress link](https://translate.wordpress.org/projects/wp-plugins/wp-idea-stream/dev/ja/default?filters%5Bterm%5D=+%3A&filters%5Buser_login%5D=&filters%5Bstatus%5D=current&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)):

- In reply to :
- Protected :
- Private :

**Comment by imath** [comment]
Thanks a lot for your feedback and your contribution to the Japanese translation of the plugin. I'll work on resolving the i18n issues asap.

**Comment by imath** [comment]
Hi @naokomc 

Latest commits above should improve the different parts you mentioned.

I only have one trouble to understand what's wrong with: 
- is the default status for all ideas
- the plugin's user profile becomes a new navigation in the BuddyPress member page.

Because these are not split sentences.. and i don't see how to improve it for the japanese translation. If you can give me some suggestions i'd be happy to apply them.

**Comment by naokomc** [comment]
@imath Thank you so much for updating the code to work better for translation. I really appreciate your prompt fixes!

#### First string
> is the default status for all ideas

This is used with a dropdown menu to read for example as "_Publish_ is the default status for all ideas"(Also, did you mean "Published" rather than "Publish" here?). In Japanese, we say "The default status for all ideas is _Publish_" to mean the same thing. Maybe it's the best if you remove this string and add more description below?
Here's what I mean:

<img width="884" alt="ideasteam" src="https://cloud.githubusercontent.com/assets/34067/13902751/82a6951c-ee9a-11e5-8365-6eb9c34480e4.png">

I'm also not really sure about what "moderation message one" mean. Is there "message two"?

#### Second string
> the plugin's user profile becomes a new navigation in the BuddyPress member page.

This one is not impossible to translate but it may be better if this whole sentence is combined into one string. I think it's ok to leave this one as is though.

> If the setting &#34;Activate BuddyPress integration&#34; is activated and you are using at least version 2.1 of BuddyPress, some nice new functionalities will be available depending on the BuddyPress components you have activated: the plugin&#39;s user profile becomes a new navigation in the BuddyPress member page.

**Comment by imath** [comment]
@naokomc thanks for your suggestion for the first string, i've committed about it.

About the seconde string, i'd agree if that was the only feature, but it's one out of a list of 4 see https://github.com/imath/wp-idea-stream/blob/2.3.2/includes/buddypress/settings.php#L123

![settings-ideastream](https://cloud.githubusercontent.com/assets/1834524/14015264/17d3e03e-f1b8-11e5-9b47-a5bee75c8cc4.png)


So i'll keep it that way.

**Comment by naokomc** [comment]
Great, all looks good. The second string ("The plugin's user profile...") is capitalized so that makes sense now.
Looking forward to the next update.
