### ISSUE TITLE
fr_FR Translations are not validated on WP.org since 2.3.0

### ISSUE THREAD

**Issue by imath** [imath/wp-idea-stream#58]
Put back the french po/mo in languages in next release and use `load_plugin_textdomain()` the right way.

**Comment by meche** [comment]
the translation to pt_BR is in progress, in which branch i can send the pull request?

**Comment by imath** [comment]
hi @meche 

Thanks a lot for your contribution.

I think it's best you use https://translate.wordpress.org/locale/pt-br/default/wp-plugins/wp-idea-stream

I'm afraid i can't maintain it within the plugin directly as i'm not Brazilian and i won't be able to refresh the translations each time i need to upgrade thte plugin. This issue is more about the french translation which i can maintain because i'm french :)

**Comment by meche** [comment]
Sure! Thank you for attention :)

**Comment by imath** [comment]
fixed in bebfbe7ebf0584bfd68dbc99bb8e6e4da26b1ac4
