### ISSUE TITLE
typo in string in tags.php 

### ISSUE THREAD

**Issue by hubwoop** [imath/wp-idea-stream#68]
I don't know if pull requests are better for this but in line 354 in wp-idea-stream\includes\ideas\tags.php is a typo. (https://github.com/imath/wp-idea-stream/blob/master/includes/ideas/tags.php#L354)

It should either read:
It looks like no ideas **have** been submitted yet
or
It looks like no **idea** has been submitted yet

and not:
It looks like no **ideas has** been submitted yet

Thanks to everyone working on this great plugin 👍

**Comment by imath** [comment]
Thanks for your feedback, i'll fix this asap.

**Comment by imath** [comment]
It will be fixed in next minor release, see above commit.

**Comment by hubwoop** [comment]
Sweet! Thank you.
