### ISSUE TITLE
Wp-idea-stream date in english

### ISSUE THREAD

**Issue by bilalkhanNQI** [imath/wp-idea-stream#70]
Hello,

We have downloaded idea stream and integrated it into a french website. First of all, thank you for this excellent plugin. Good job, it is very useful.

We have one little problem with it. Since the site is in French, the date on the idea list is in "US version". That means it shows the month first and the date later (MM/DD/YEAR). We would like it to be (DD/MM/YEAR), french version.

Since the website is a community website, not accessible to everyone I have included a screen shot. 

Thanks,

![image](https://cloud.githubusercontent.com/assets/27365978/24970426/85617cbc-1fb4-11e7-8ff9-1d7828faf21a.png)

**Comment by imath** [comment]
Hi,

Is the date format set to french in the WordPress global settings ? Because WP Idea Stream use this to format the date.

imath.
http://profiles.wordpress.org/imath/

**Comment by bilalkhanNQI** [comment]
Hello,

Thanks for your reply. It worked out.

Regards,

Bilal

2017-04-12 20:15 GMT+02:00 imath <notifications@github.com>:
